spec_version: 2-preview
description: ansible hello world

inputs:
  agent:
    type: agent

grains:
  create-ec2:
    kind: terraform
    spec:
      source:
        path: terraform/create-ec2-instance
        store: test-spec2-public
      agent:
        name: '{{.inputs.agent}}'
      env-vars:
        - TF_LOG: debug
      outputs:
        - public_ip
        - password
        
  install-nginx:
    kind: ansible
    depends-on: create-ec2
    spec: 
      source:
        store: test-spec2-public
        path: ansible/install_nginx_on_ec2.yaml
      agent:
        name: '{{ .inputs.agent }}'
      inventory-file:
        all:
          hosts:
            ec2_instance:
              ansible_host: '{{ .grains.create-ec2.outputs.public_ip }}'
              ansible_user: 'ubuntu'
              ansible_password: '{{ .grains.create-ec2.outputs.public_ip }}'
          vars:
            ansible_become: yes
            ansible_become_method: sudo
            ansible_become_pass: '{{ .grains.create-ec2.outputs.public_ip }}'
              