spec_version: 2

description: description text 2

inputs:
  compute_service_name:
    type: agent     
  release:
    type: string
    default: ""

outputs:
  output1:
    value: 'https://{{.grains.nginx-simple.scripts.post-helm-install.outputs.output1}}'
    kind: link
  output2:
    value: '{{.grains.nginx-simple.scripts.post-helm-install.outputs.output2}}'

grains:
  nginx-simple:
    kind: helm
    spec:
      source:
        store:k9sa test-spec2-public
        path: helm/nginx-test
      agent:
        name: '{{.inputs.compute_service_name}}'
      commands:
        - list && cp -R ${workspace_dir1}/helm/nginx-test/ci ${WORK_DIR}/helm/nginx-test/directory_from_dir1
        - list && cp -R ${workspace_dir2}/terraform/simple-tf-module/main.tf ${WORK_DIR}/helm/nginx-test/file_from_dir2
        - dep up helm/nginx-test
      inputs:
        - replicaSet: 1
        - input_2: 'test'
        - input_3: 3
      workspace-directories:
        - source: 
            name: workspace_dir1
            store: test-spec2-public
            # path: helm/nginx-test/values.yaml
            commit: 25dbe596bb083ca9346692f3cc846cd061f30a14
        - source: 
            name: workspace_dir2
            store: iac-samples
            # commit: eb7bf547f916ff11f0f95e35fb1e8c6fd6535ce1
      values-files:
        - source: 
            store: test-spec2-public
            path: helm/nginx-test/values.yaml
            commit: 25dbe596bb083ca9346692f3cc846cd061f30a14
        - source: 
            store: test-spec2-public
            # path: helm/nginx-test/values.yaml
            commit: ff02f93408b9034069e80efaed45524a700e069a        
        - source: 
            store: iac-samples
            # path: helm/nginx-test/values.yaml
            # commit: eb7bf547f916ff11f0f95e35fb1e8c6fd6535ce1
      command-arguments: '--version 3.0.0'
      env-vars:
        - test: newValue
      scripts:
        post-helm-install:
          source:
            store: test-spec2-public
            path:  scripts/post-install-script.sh            
          outputs:
            - output1
            - output2
